services:
  proxy:
    image: ${DOCKER_REGISTRY}nginx-no-default:${DOCKER_TAG:-latest}
    restart: unless-stopped
    network_mode: host
    volumes:
      - "proxy-config:/etc/nginx/conf.d"

volumes:
  proxy-config:
    name: "proxy-config"
